#!/bin/bash -x
#
# Create a tar.gz dist of the vac agent, to be used by rpmbuild.
# Author: Lasse Karstensen <lkarsten@varnish-software.com>

TMPDIR=/tmp/foo$$
PREVDIR=$PWD

TOPDIR=/tmp/varnish-agent-rpm/

# someone will hate me for this some day..
#echo "%_topdir $TOPDIR" > ~/.rpmmacros

if [ ! -d "$TOPDIR" ]; then
    mkdir -p $TOPDIR
    for i in SOURCES SPECS BUILD RPMS RPMS/x64_64; do
        mkdir -p $TOPDIR/$i
    done
fi

mkdir -p $TMPDIR/varnish-agent-trunk/
cp -r .. $TMPDIR/varnish-agent-trunk/

cd $TMPDIR
tar zcf $TOPDIR/SOURCES/varnish-agent-trunk.tar.gz varnish-agent-trunk
rm -rf $TMPDIR

cd $PREVDIR

